CREATE TABLE IF NOT EXISTS film (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    release_date DATE NOT NULL,
    duration INTEGER,
    mpa_id INTEGER NOT NULL,
    FOREIGN KEY (mpa_id) REFERENCES mpa(mpa_id)
);

-- Создание таблицы Genre
CREATE TABLE IF NOT EXISTS genre (
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

-- Создание таблицы Film_Genre (связь "многие ко многим" между Film и Genre)
CREATE TABLE IF NOT EXISTS genre_film (
    genre_film_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    film_id INTEGER,
    genre_id INTEGER,
    PRIMARY KEY (genre_film_id),
    FOREIGN KEY (film_id) REFERENCES film(id),
    FOREIGN KEY (genre_id) REFERENCES genre(genre_id)
);

-- Создание таблицы Mpa
CREATE TABLE IF NOT EXISTS mpa (
    mpa_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

-- Создание таблицы User
CREATE TABLE IF NOT EXISTS user (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    login VARCHAR(255) NOT NULL,
    username VARCHAR(255),
    birthday DATE NOT NULL
);

-- Создание таблицы Friends
CREATE TABLE IF NOT EXISTS friends (
    user_id INTEGER,
    friend_id INTEGER,
    PRIMARY KEY (user_id, friend_id),
    FOREIGN KEY (user_id) REFERENCES user(id),
    FOREIGN KEY (friend_id) REFERENCES user(id)
);

-- Создание таблицы Like_Film (связь "многие ко многим" между User и Film)
CREATE TABLE IF NOT EXISTS like_film (
    user_id INTEGER,
    film_id INTEGER,
    PRIMARY KEY (user_id, film_id),
    FOREIGN KEY (user_id) REFERENCES user(id),
    FOREIGN KEY (film_id) REFERENCES film(id)
);

-- Вставка данных в таблицу Genre
INSERT INTO genre (name)
VALUES ('Комедия'),
    ('Драма'),
    ('Мультфильм'),
    ('Триллер'),
    ('Документальный'),
    ('Боевик');

-- Вставка данных в таблицу Mpa
INSERT INTO mpa (name)
VALUES ('G'),
       ('PG'),
       ('PG-13'),
       ('R'),
       ('NC-17');